version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - esnetwork

  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - esnetwork

volumes:
  esdata:
    driver: local

networks:
  esnetwork:
